// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package org.example.auth.proto;

public final class AuthProto {
  private AuthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_DeliverTokenReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_DeliverTokenReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_VerifyTokenReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_VerifyTokenReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_DeliveryResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_DeliveryResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_VerifyResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_VerifyResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nauth.proto\022\004auth\"\"\n\017DeliverTokenReq\022\017\n" +
      "\007user_id\030\001 \001(\005\"\037\n\016VerifyTokenReq\022\r\n\005toke" +
      "n\030\001 \001(\t\"\035\n\014DeliveryResp\022\r\n\005token\030\001 \001(\t\"\031" +
      "\n\nVerifyResp\022\013\n\003res\030\001 \001(\0102\215\001\n\013AuthServic" +
      "e\022@\n\021DeliverTokenByRPC\022\025.auth.DeliverTok" +
      "enReq\032\022.auth.DeliveryResp\"\000\022<\n\020VerifyTok" +
      "enByRPC\022\024.auth.VerifyTokenReq\032\020.auth.Ver" +
      "ifyResp\"\000B3\n$org.example.userauth.docs.p" +
      "roto.AuthB\tAuthProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_auth_DeliverTokenReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_DeliverTokenReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_DeliverTokenReq_descriptor,
        new String[] { "UserId", });
    internal_static_auth_VerifyTokenReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_auth_VerifyTokenReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_VerifyTokenReq_descriptor,
        new String[] { "Token", });
    internal_static_auth_DeliveryResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_auth_DeliveryResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_DeliveryResp_descriptor,
        new String[] { "Token", });
    internal_static_auth_VerifyResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_auth_VerifyResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_VerifyResp_descriptor,
        new String[] { "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
