// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package org.example.auth.proto;

public interface DeliverTokenReqOrBuilder extends
        // @@protoc_insertion_point(interface_extends:auth.DeliverTokenReq)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 user_id = 1;</code>
     *
     * @return The userId.
     */
    int getUserId();
}
