// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package org.example.auth.proto;

public interface VerifyRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.VerifyResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool res = 1;</code>
   * @return The res.
   */
  boolean getRes();
}
