// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package org.example.auth.proto;

public interface VerifyTokenReqOrBuilder extends
        // @@protoc_insertion_point(interface_extends:auth.VerifyTokenReq)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string token = 1;</code>
     *
     * @return The token.
     */
    String getToken();

    /**
     * <code>string token = 1;</code>
     *
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
    getTokenBytes();
}
