// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.example.userservice.proto;

public interface LoginRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User.LoginResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
